# Generated by Django 3.2.2 on 2021-06-06 04:06

import analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viscosity",
                    models.FloatField(
                        validators=[analysis.models.Analysis.validate_positive_float],
                        verbose_name="viscosity",
                    ),
                ),
                (
                    "diameter",
                    models.FloatField(
                        validators=[analysis.models.Analysis.validate_positive_float],
                        verbose_name="diameter",
                    ),
                ),
                (
                    "flow",
                    models.FloatField(
                        validators=[analysis.models.Analysis.validate_positive_float],
                        verbose_name="flow",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Analyses",
            },
        ),
    ]
