# Generated by Django 3.2.2 on 2021-06-06 15:02

import analysis.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="diameter",
            field=models.FloatField(
                help_text="Pipe Diameter in m",
                validators=[analysis.models.Analysis.validate_positive_float],
                verbose_name="diameter",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="flow",
            field=models.FloatField(
                help_text="Fluid flow in the pipe in m³/s",
                validators=[analysis.models.Analysis.validate_positive_float],
                verbose_name="flow",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="viscosity",
            field=models.FloatField(
                help_text="Kinematic Viscosity in St",
                validators=[analysis.models.Analysis.validate_positive_float],
                verbose_name="viscosity",
            ),
        ),
    ]
